version: "3"

services:
  db:
    image: mongo
    volumes:
      - ./db-data/mongo/:/data/db
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password

  splash:
    image: scrapinghub/splash
    ports:
      - "8050:8050"

  scrapy:
    build: .
    volumes:
      - .:/code
    depends_on:
      - splash
      - db
