version: "3"

services:
  db:
    image: mongo
    volumes:
      - db-data:/data/db
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password

  splash:
    image: scrapinghub/splash
    ports:
      - "8050:8050"

  scrapy:
    build: .
    volumes:
      - ./scrapy.cfg:/app/scrapy.cfg
      - ./output:/app/output
    environment:
      - MONGO_USERNAME=admin
      - MONGO_PASSWORD=password
    depends_on:
      - splash
      - db

volumes:
  db-data:
  